# Generated by Django 5.1.7 on 2025-04-23 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_posts_users_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
