# Generated by Django 5.2 on 2025-05-03 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_rename_posts_post_rename_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=150)),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField()),
                ('caption', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AddField(
            model_name='comment',
            name='made_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.user'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='in_highlight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.highlight'),
        ),
        migrations.AddField(
            model_name='photo',
            name='included_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.highlight'),
        ),
    ]
