# Generated by Django 5.2 on 2025-05-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_comment_highlight_photo_delete_post_alter_user_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
