# Generated by Django 5.2 on 2025-05-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_rename_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='person@example.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_memory',
            field=models.CharField(default='No memory yet...', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='qwerty', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pictures/'),
        ),
    ]
