# Generated by Django 5.2 on 2025-05-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_profile_email_profile_favorite_memory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile.jpg', upload_to='map/templates/profile-page/images/'),
        ),
    ]
